### ISSUE TITLE
点击连接时，报空指针异常，请问应该怎么修正？

### ISSUE THREAD

**Issue by android1601** [Jasonchenlijian/FastBle#24]
com.bdk.blesample E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
com.bdk.blesample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   java.lang.NullPointerException
                                                                       at java.lang.String.valueOf(String.java:1574)
                                                                       at com.clj.blesample.OperateActivity.showConnectState(OperateActivity.java:263)
                                                                       at com.clj.blesample.OperateActivity.access$300(OperateActivity.java:34)
                                                                       at com.clj.blesample.OperateActivity$3$1.run(OperateActivity.java:169)
                                                                       at android.os.Handler.handleCallback(Handler.java:730)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                       at android.os.Looper.loop(Looper.java:137)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5136)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:525)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by Jasonchenlijian** [comment]
已修正
