### ISSUE TITLE
经常出现sending message to a Handler on a dead thread这个警告

### ISSUE THREAD

**Issue by kangshaopeng** [Jasonchenlijian/FastBle#257]
java.lang.IllegalStateException: Handler (com.clj.fastble.scan.BleScanPresenter$ScanHandler) {9610773} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:646)
        at android.os.Handler.sendMessageAtTime(Handler.java:612)
        at android.os.Handler.sendMessageDelayed(Handler.java:582)
        at android.os.Handler.sendMessage(Handler.java:519)
        at com.clj.fastble.scan.BleScanPresenter.onLeScan(BleScanPresenter.java:98)
        at android.bluetooth.BluetoothAdapter$2.onScanResult(BluetoothAdapter.java:2356)
        at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:418)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6221)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
经常出现这个警告

**Comment by Jasonchenlijian** [comment]
你好，这个警告是由于扫描完成（或找到指定设备对象）之后，app端异步依然异步接收到扫描设备的回调导致的bug，对程序功能本身不会有影响。
在2.3.0版本上已修复这个问题。
