### ISSUE TITLE
在Android 4.3,level 18出现停止扫描出现空指针

### ISSUE THREAD

**Issue by GoAheadComeOn** [Jasonchenlijian/FastBle#300]
bug为线上统计bug，

具体日志如下
 java.lang.NullPointerException
com.clj.fastble.scan.BleScanner.stopLeScan(BleScanner.java:126)

1 android.bluetooth.BluetoothAdapter$GattCallbackWrapper.stopLeScan(BluetoothAdapter.java:1855)
--
2 android.bluetooth.BluetoothAdapter.stopLeScan(BluetoothAdapter.java:1799)
3 com.clj.fastble.scan.BleScanner.stopLeScan(BleScanner.java:126)
4 com.clj.fastble.scan.BleScanPresenter$1.run(BleScanPresenter.java:120)
5 android.os.Handler.handleCallback(Handler.java:730)
6 android.os.Handler.dispatchMessage(Handler.java:92)
7 android.os.Looper.loop(Looper.java:137)
8 android.app.ActivityThread.main(ActivityThread.java:5528)
9 java.lang.reflect.Method.invokeNative(Native Method)
10 java.lang.reflect.Method.invoke(Method.java:525)
11 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
12 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
13 dalvik.system.NativeStart.main(Native Method)

**Comment by DituLin** [comment]
扫描的时候也出现 NPE
fastble： 2.3.4
手机：华为 INE-AL00
系统：android 8.1.0 

==================
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.bluetooth.gatt.ScanManager.registerScanner(java.util.UUID)' on a null object reference
    at android.os.Parcel.readException(Parcel.java:2022)
    at android.os.Parcel.readException(Parcel.java:1962)
    at android.bluetooth.IBluetoothGatt$Stub$Proxy.registerScanner(IBluetoothGatt.java:957)
    at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.startRegistration(BluetoothLeScanner.java:428)
    at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:241)
    at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:133)
    at android.bluetooth.BluetoothAdapter.startLeScan(BluetoothAdapter.java:2557)
    at com.clj.fastble.scan.BleScanner.startLeScan(BleScanner.java:123)
    at com.clj.fastble.scan.BleScanner.scanAndConnect(BleScanner.java:106)
    at com.clj.fastble.BleManager.scanAndConnect(BleManager.java:331)
    at com.hmkj.blelib.ble.AccessManager.onBleScan(AccessManager.java:210)
    at com.hmkj.blelib.ble.AccessManager.access$900(AccessManager.java:32)
    at com.hmkj.blelib.ble.AccessManager$5.handleMessage(AccessManager.java:495)
    at android.os.Handler.dispatchMessage(Handler.java:109)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7555)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
