### ISSUE TITLE
不开启蓝牙进行扫描后带来的问题

### ISSUE THREAD

**Issue by Symous** [Jasonchenlijian/FastBle#309]
当我们不启动蓝牙，但是仍然调用扫描方法的话，当调用bleManager.cancelScan()后，会有如下报错信息：
Attempt to invoke virtual mehotd 'boolean android.os.HandlerThread.quit()' on a null object reference.
当然我可以通过自己判断蓝牙是否开启等方法来决定是否调用cancelScan。 :)

**Comment by Jasonchenlijian** [comment]
谢谢你的反馈

**Comment by JustTrust** [comment]
Faced same issue
com.myApp E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.HandlerThread.quit()' on a null object reference
        at com.clj.fastble.scan.BleScanPresenter.notifyScanStopped(BleScanPresenter.java:207)
        at com.clj.fastble.scan.BleScanner.stopLeScan(BleScanner.java:131)
        at com.clj.fastble.BleManager.cancelScan(BleManager.java:385)
        at myApp.bluetooth.BluetoothLowEnergy.stopObservingBlDevices(BluetoothLowEnergy.kt:94)
