### ISSUE TITLE
崩溃le

### ISSUE THREAD

**Issue by douya40** [Jasonchenlijian/FastBle#482]
java.lang.NullPointerException: println needs a message
        at android.util.Log.println_native(Native Method)
        at android.util.Log.i(Log.java:166)
        at com.xunyi.etogo.ui.activity.LoginActivity$8.onScanning(LoginActivity.java:240)
        at com.clj.fastble.scan.BleScanner$1.onScanning(BleScanner.java:63)
        at com.clj.fastble.scan.BleScanPresenter$3.run(BleScanPresenter.java:176)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6823)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by Android-wangmeng** [comment]
这是由于你自己的打印出现的空指针，和框架并没有什么关系。（LoginActivity.java:240）
