### ISSUE TITLE
Exception if disconnect while dialog shown

### ISSUE THREAD

**Issue by hassance3** [Jasonchenlijian/FastBle#485]
- Connect.
- Click on a characteristic.
- While the dialog [Read / Write] is shown, disconnected the other BLE device.

```
E/WindowManager: android.view.WindowLeaked: Activity com.clj.blesample.operation.OperationActivity has leaked window DecorView@1150d3c[] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:511)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:338)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.app.Dialog.show(Dialog.java:322)
        at android.support.v7.app.AlertDialog$Builder.show(AlertDialog.java:1006)
        at com.clj.blesample.operation.CharacteristicListFragment$1.onItemClick(CharacteristicListFragment.java:82)
        at android.widget.AdapterView.performItemClick(AdapterView.java:315)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1204)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3321)
        at android.widget.AbsListView.onTouchUp(AbsListView.java:4393)
        at android.widget.AbsListView.onTouchEvent(AbsListView.java:4093)
        at android.view.View.dispatchTouchEvent(View.java:10062)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2776)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2408)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:435)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1836)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3101)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:397)
        at android.view.View.dispatchPointerEvent(View.java:10293)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4936)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4795)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4301)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4354)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4320)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4467)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4328)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4524)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4301)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4354)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4320)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4328)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4301)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6825)
E/WindowManager:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6799)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6742)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6997)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:328)
        at android.os.Looper.loop(Looper.java:151)
        at android.app.ActivityThread.main(ActivityThread.java:6304)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
D/WindowClient: Remove from mViews: DecorView@1150d3c[], this = android.view.WindowManagerGlobal@9364d88
D/Surface: Surface::disconnect(this=0x794fe58800,api=1)
D/GraphicBuffer: unregister, handle(0x7933749f40) (w:44 h:197 s:48 f:0x1 u:0x000b00)
    unregister, handle(0x79345fc980) (w:44 h:197 s:48 f:0x1 u:0x000b00)
D/Surface: Surface::disconnect(this=0x794fe58800,api=1)
D/WindowClient: Remove from mViews: android.widget.LinearLayout{a082239 V.E...... ........ 0,0-197,44}, this = android.view.WindowManagerGlobal@9364d88
```

**Comment by kingiis** [comment]
通常断开链接时,我都是放在service里处理的,因为一般涉及关闭页面等会泄露的操作,配合eventbus来做吧


Usually, when I disconnect a link, I put it in the service, because it usually involves closing the page and other operations that will leak. Please cooperate with eventbus
